import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

interface FormField {
  id: string;
  label: string;
  type: string;
  options?: string[];
  required: boolean;
  helpText?: string;
  value: string | string[];
}

export const generatePDF = (formData: { [key: string]: FormField[] }): void => {
  // Create a temporary div to render our form data
  const tempDiv = document.createElement('div');
  tempDiv.style.padding = '20px';
  tempDiv.style.fontFamily = 'Arial, sans-serif';
  tempDiv.style.width = '210mm';
  tempDiv.style.position = 'absolute';
  tempDiv.style.left = '-9999px';
  
  // Add a title
  const title = document.createElement('h1');
  title.textContent = 'Health Form';
  title.style.textAlign = 'center';
  title.style.marginBottom = '20px';
  title.style.color = '#0D9488';
  tempDiv.appendChild(title);
  
  // Iterate through form sections
  Object.entries(formData).forEach(([sectionKey, fields]) => {
    // Create section header
    const sectionHeader = document.createElement('h2');
    sectionHeader.textContent = sectionKey.replace(/([A-Z])/g, ' $1').trim();
    sectionHeader.style.marginTop = '20px';
    sectionHeader.style.marginBottom = '10px';
    sectionHeader.style.color = '#0D9488';
    tempDiv.appendChild(sectionHeader);
    
    // Create a table for the section's fields
    const table = document.createElement('table');
    table.style.width = '100%';
    table.style.borderCollapse = 'collapse';
    table.style.marginBottom = '20px';
    
    // Add fields to the table
    fields.forEach((field) => {
      const row = document.createElement('tr');
      
      const labelCell = document.createElement('td');
      labelCell.textContent = field.label + (field.required ? ' *' : '');
      labelCell.style.padding = '8px';
      labelCell.style.border = '1px solid #ddd';
      labelCell.style.width = '40%';
      labelCell.style.fontWeight = 'bold';
      row.appendChild(labelCell);
      
      const valueCell = document.createElement('td');
      valueCell.style.padding = '8px';
      valueCell.style.border = '1px solid #ddd';
      
      // Format the value based on field type
      if (field.type === 'checkbox' && Array.isArray(field.value)) {
        valueCell.textContent = field.value.join(', ');
      } else {
        valueCell.textContent = field.value.toString();
      }
      
      row.appendChild(valueCell);
      table.appendChild(row);
    });
    
    tempDiv.appendChild(table);
  });
  
  // Add footer with disclaimer
  const footer = document.createElement('p');
  footer.textContent = 'This form was generated by CareEase Hub. The information provided is for healthcare purposes only.';
  footer.style.marginTop = '30px';
  footer.style.fontSize = '12px';
  footer.style.fontStyle = 'italic';
  footer.style.color = '#666';
  tempDiv.appendChild(footer);
  
  document.body.appendChild(tempDiv);
  
  // Use html2canvas to convert the div to an image
  html2canvas(tempDiv).then(canvas => {
    const imgData = canvas.toDataURL('image/png');
    const pdf = new jsPDF('p', 'mm', 'a4');
    const imgProps = pdf.getImageProperties(imgData);
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = (imgProps.height * pdfWidth) / imgProps.width;
    
    pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
    pdf.save('health-form.pdf');
    
    // Clean up
    document.body.removeChild(tempDiv);
  });
};